version: '3.8'

services:
  weather:
    build: .
    restart: always
    depends_on:
      - postgres_db
    ports:
      - '8080:8080'
  postgres_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: Weather
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'


